name: Backend CI (Express)

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint || echo "no lint script"

      - name: Run tests
        run: npm test || echo "no tests configured"

      - name: Build
        run: npm run build || echo "no build step"
